/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MerrittR_RegSys_V2.gui;

import com.mycompany.merrittr_regsys_v2.Student;
import com.mycompany.merrittr_regsys_v2.InternationalStudent;
import com.mycompany.merrittr_regsys_v2.Section;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
        
        
/**
 *
 * @author Ryan
 */
public class StudentInfo extends javax.swing.JFrame {

    DefaultListModel lm;
    DefaultTableModel tm;
    Student s = new InternationalStudent(227,"Ricky", "Martinez");
    
    public StudentInfo() {
        initComponents();
        lm = new DefaultListModel();
        listCourses.setModel(lm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        tbxStuID = new javax.swing.JTextField();
        tbxStuName = new javax.swing.JTextField();
        tbxStuLName = new javax.swing.JTextField();
        tbxTuition = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listCourses = new javax.swing.JList<>();
        btnDrop = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student Registration System");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("StudentID");

        jLabel2.setText("First Name");

        jLabel3.setText("Last Name");

        jLabel4.setText("Tuition/Fees Due $");
        jLabel4.setToolTipText("");

        jLabel5.setText("Schedule");

        jScrollPane1.setViewportView(listCourses);

        btnDrop.setText("Drop");
        btnDrop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDropMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(tbxTuition, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGap(13, 13, 13)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(tbxStuID, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                            .addComponent(tbxStuLName, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tbxStuName, javax.swing.GroupLayout.Alignment.LEADING))))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDrop)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbxStuID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbxStuName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbxStuLName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(btnDrop)
                        .addGap(97, 97, 97)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tbxTuition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
        
        Section busProg = new Section("Business Programming", "12345", "T/R", 3, "3-4");
        Section projMan = new Section("Project Management", "67890", "T/R", 3, "5-6");
        Section busObj = new Section("Business Objects", "65498", "M/W", 3, "3-4");
        Section eComm = new Section ("E-Commerce", "32165", "W/F", 3, "1-2");
       
        s.addSection(busProg);
        s.addSection(projMan);
        s.addSection(busObj);
        s.addSection(eComm);
        
        tbxStuID.setText(String.valueOf(s.getId()));
        tbxStuName.setText(s.getName());
        tbxStuLName.setText(s.getLname());
        tbxStuID.setEditable(false);
        tbxStuName.setEditable(false);
        tbxStuLName.setEditable(false);
        
//        String row1 = busProg.toString();
//        String row2 = projMan.toString();
//        String row3 = busObj.toString();
//        String row4 = eComm.toString();
//        
//        lm.addElement(row1);
//        lm.addElement(row2);
//        lm.addElement(row3);
//        lm.addElement(row4);
        
        for (int i=0; i<s.getCurEnr().size(); i++) {
            lm.addElement(String.format("%s | Section: %s | Credits: %d", s.getCurEnr().get(i).getCourseName(), s.getCurEnr().get(i).getSectionNumber(), s.getCurEnr().get(i).getCredits()));
        }
        
        tbxTuition.setText(String.valueOf(s.calcTuitionFees()));   
    }//GEN-LAST:event_formWindowOpened

    private void btnDropMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDropMouseClicked
        
      int[] toDrop = listCourses.getSelectedIndices();
      int count = toDrop.length;
      String msg = "Are you sure you would like to drop the selected section(s)?";
      
      int confirm = JOptionPane.showConfirmDialog(this, msg, "Confirm Drop", JOptionPane.YES_NO_OPTION);
      
      if (confirm == JOptionPane.YES_OPTION) {
                 
        for (int i=0; i<count; i++) {
            s.dropSection(s.getCurEnr().get(listCourses.getSelectedIndex()));
            lm.removeElementAt(listCourses.getSelectedIndex());
        }
      }
      
      int sumCredits = 0;
      for (int i = 0; i<s.getCurEnr().size(); i++) {
          
          sumCredits += s.getCurEnr().get(i).getCredits();
      }
      
      String warn = "Total credits dropped below F-1 Visa minimum (9)";
      if (s instanceof InternationalStudent && sumCredits < 9) {
          JOptionPane.showMessageDialog(this, warn, "Warning", JOptionPane.WARNING_MESSAGE);
      }
        
      tbxTuition.setText(String.valueOf(s.calcTuitionFees()));  
      
// Testing s.drop from previous for loop. Adds curEnr to list model, enrolled classes are duplicated.      
//        for (int i=0; i<s.getCurEnr().size(); i++) {
//            lm.addElement(String.format("%s, %s, %d", s.getCurEnr().get(i).getCourseName(), s.getCurEnr().get(i).getSectionNumber(), s.getCurEnr().get(i).getCredits()));
//        }   
    }//GEN-LAST:event_btnDropMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDrop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JList<String> listCourses;
    private javax.swing.JTextField tbxStuID;
    private javax.swing.JTextField tbxStuLName;
    private javax.swing.JTextField tbxStuName;
    private javax.swing.JTextField tbxTuition;
    // End of variables declaration//GEN-END:variables
}
